services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always
    environment:
      - PORT=8000
      - PYTHONPATH=/app

  extension:
    build:
      context: ./extension
      args:
        - VITE_API_URL=https://airtouch-backend.onrender.com
    ports:
      - "5173:5173"
    volumes:
      - ./extension:/app
      - ./extension/dist:/app/dist
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=https://airtouch-backend.onrender.com
    depends_on:
      - backend
